# Generated by Django 4.1.6 on 2023-02-03 23:25

from django.db import migrations, models
import django.db.models.deletion
import storeproduct.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=350)),
                ('order_category', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('number_document_identity', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=500)),
                ('job_position', models.CharField(max_length=500)),
                ('address_institution', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=5000)),
                ('image_product', models.TextField(max_length=255)),
                ('inventory', models.PositiveSmallIntegerField(validators=[storeproduct.models.validate_min_value])),
                ('unit_price', models.FloatField(default=0)),
                ('code_product', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeproduct.categoryproduct')),
                ('unit_measure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeproduct.unitmeasure')),
            ],
        ),
        migrations.CreateModel(
            name='EntryOrderStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_order', models.PositiveIntegerField()),
                ('invoice_number', models.CharField(max_length=35)),
                ('total_price_order', models.FloatField(default=0)),
                ('code_string', models.TextField(max_length=5000)),
                ('date_register_order', models.DateTimeField(auto_now_add=True)),
                ('date_updated_order', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeproduct.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='DetailOrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0)),
                ('entry_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeproduct.entryorderstore')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storeproduct.product')),
            ],
        ),
    ]
