# Generated by Django 4.1.6 on 2023-02-04 15:38

from django.db import migrations, models
import storeproduct.models


class Migration(migrations.Migration):

    dependencies = [
        ('storeproduct', '0002_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(default=0, validators=[storeproduct.models.validate_price_product]),
        ),
    ]
